# Generated by Django 6.0 on 2026-01-07 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=300)),
                (
                    "icon",
                    models.TextField(
                        default='<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" /></svg>',
                        help_text="SVG code or icon class (e.g., Heroicons SVG)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        help_text="Column header (e.g., 'Product', 'Company')",
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Footer Link",
                "verbose_name_plural": "Footer Links",
                "ordering": ["column_name", "order"],
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="landing/integrations/"
                    ),
                ),
                (
                    "icon_svg",
                    models.TextField(
                        blank=True, help_text="Alternative: SVG code for icon"
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LandingPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="RoyalERP Chatbot", max_length=100),
                ),
                (
                    "logo_image",
                    models.ImageField(blank=True, null=True, upload_to="landing/logo/"),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="landing/favicon/"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#1e3a5f", help_text="Deep navy/indigo", max_length=7
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6366f1", help_text="Indigo/purple", max_length=7
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#ec4899", help_text="Pink/lavender", max_length=7
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Run your ERP with an AI Chatbot", max_length=200
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Automate inventory, accounts, sales insights, and reporting with intelligent AI assistance."
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Dashboard mockup",
                        null=True,
                        upload_to="landing/hero/",
                    ),
                ),
                (
                    "primary_cta_label",
                    models.CharField(default="Get Started", max_length=50),
                ),
                ("primary_cta_url", models.URLField(default="#pricing")),
                (
                    "secondary_cta_label",
                    models.CharField(default="Book Demo", max_length=50),
                ),
                ("secondary_cta_url", models.URLField(default="#demo")),
                (
                    "final_cta_title",
                    models.CharField(default="Ready to Launch?", max_length=200),
                ),
                (
                    "final_cta_subtitle",
                    models.TextField(
                        default="Join thousands of businesses automating their ERP with AI."
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        default="RoyalERP Chatbot - AI-Powered ERP Assistant",
                        max_length=70,
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        default="Automate your ERP operations with AI. Smart inventory, accounts, sales insights, and reporting.",
                        max_length=160,
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="landing/og/"),
                ),
                (
                    "footer_about",
                    models.TextField(
                        blank=True,
                        default="RoyalERP Chatbot helps businesses automate their ERP operations with intelligent AI assistance.",
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© 2024 RoyalERP. All rights reserved.", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing Page Settings",
                "verbose_name_plural": "Landing Page Settings",
            },
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.CharField(
                        help_text="e.g., '$29' or 'Custom'", max_length=50
                    ),
                ),
                (
                    "period",
                    models.CharField(blank=True, default="/month", max_length=50),
                ),
                ("bullets", models.TextField(help_text="One feature per line")),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Highlight this plan"),
                ),
                ("cta_label", models.CharField(default="Get Started", max_length=50)),
                ("cta_url", models.URLField(default="#")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pricing Plan",
                "verbose_name_plural": "Pricing Plans",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'automation', 'use-cases')",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField(blank=True)),
                (
                    "bullets",
                    models.TextField(blank=True, help_text="One bullet point per line"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="landing/sections/"
                    ),
                ),
                (
                    "layout_type",
                    models.CharField(
                        choices=[
                            ("LEFT_IMAGE", "Image on Left"),
                            ("RIGHT_IMAGE", "Image on Right"),
                        ],
                        default="LEFT_IMAGE",
                        max_length=20,
                    ),
                ),
                (
                    "background_style",
                    models.CharField(
                        choices=[
                            ("WHITE", "White"),
                            ("LIGHT", "Light Gray/Blue"),
                            ("GRADIENT", "Gradient"),
                        ],
                        default="WHITE",
                        max_length=20,
                    ),
                ),
                ("cta_label", models.CharField(blank=True, max_length=50)),
                ("cta_url", models.URLField(blank=True)),
                ("secondary_cta_label", models.CharField(blank=True, max_length=50)),
                ("secondary_cta_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Section Block",
                "verbose_name_plural": "Section Blocks",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StatCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "value",
                    models.CharField(
                        help_text="e.g., '10K+', '500+', '99%'", max_length=50
                    ),
                ),
                ("icon", models.TextField(blank=True, help_text="Optional SVG icon")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Stat Counter",
                "verbose_name_plural": "Stat Counters",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="landing/testimonials/"
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UseCasePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "icon",
                    models.TextField(
                        blank=True, default="", help_text="Optional SVG icon"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Use Case",
                "verbose_name_plural": "Use Cases",
                "ordering": ["order"],
            },
        ),
    ]
