# Generated by Django 6.0 on 2026-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="faq_subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="faq_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="features_subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="features_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="integrations_footer_text",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="integrations_subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="integrations_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="pricing_featured_label",
            field=models.CharField(
                blank=True, help_text="Label for featured plan badge", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="pricing_subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="pricing_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="testimonials_subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="testimonials_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="use_cases_subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="use_cases_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.TextField(
                blank=True, help_text="SVG code or icon class (e.g., Heroicons SVG)"
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="copyright_text",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="final_cta_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="final_cta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="footer_about",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="hero_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="hero_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="primary_cta_label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="primary_cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="secondary_cta_label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="secondary_cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="seo_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="site_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="bullets",
            field=models.TextField(blank=True, help_text="One feature per line"),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="cta_label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="period",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
