# Generated by Django 6.0 on 2026-01-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0002_landingpagesettings_faq_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="hero_video",
            field=models.FileField(
                blank=True,
                help_text="Optional demo video (MP4)",
                null=True,
                upload_to="landing/hero/",
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="hero_video_url",
            field=models.URLField(blank=True, help_text="Or YouTube/Vimeo embed URL"),
        ),
        migrations.AddField(
            model_name="sectionblock",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Demo video (MP4)",
                null=True,
                upload_to="landing/sections/",
            ),
        ),
        migrations.AddField(
            model_name="sectionblock",
            name="video_url",
            field=models.URLField(blank=True, help_text="Or YouTube/Vimeo embed URL"),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Dashboard mockup/screenshot",
                null=True,
                upload_to="landing/hero/",
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="site_name",
            field=models.CharField(
                blank=True, help_text="e.g., Royal ERP Chatbot", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sectionblock",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Screenshot/mockup image",
                null=True,
                upload_to="landing/sections/",
            ),
        ),
    ]
