# Generated by Django 6.0 on 2026-01-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0003_landingpagesettings_hero_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="hero_video",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="hero_video_url",
        ),
        migrations.RemoveField(
            model_name="sectionblock",
            name="video",
        ),
        migrations.RemoveField(
            model_name="sectionblock",
            name="video_url",
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Dashboard mockup",
                null=True,
                upload_to="landing/hero/",
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="site_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="sectionblock",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="landing/sections/"
            ),
        ),
    ]
