# Generated by Django 6.0 on 2026-01-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0004_remove_landingpagesettings_hero_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="faq_subtitle",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="faq_title",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="features_subtitle",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="features_title",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="integrations_footer_text",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="integrations_subtitle",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="integrations_title",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="pricing_featured_label",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="pricing_subtitle",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="pricing_title",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="testimonials_subtitle",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="testimonials_title",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="use_cases_subtitle",
        ),
        migrations.RemoveField(
            model_name="landingpagesettings",
            name="use_cases_title",
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.TextField(
                default='<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" /></svg>',
                help_text="SVG code or icon class (e.g., Heroicons SVG)",
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="copyright_text",
            field=models.CharField(
                default="© 2024 RoyalERP. All rights reserved.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="final_cta_subtitle",
            field=models.TextField(
                default="Join thousands of businesses automating their ERP with AI."
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="final_cta_title",
            field=models.CharField(default="Ready to Launch?", max_length=200),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="footer_about",
            field=models.TextField(
                blank=True,
                default="RoyalERP Chatbot helps businesses automate their ERP operations with intelligent AI assistance.",
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="hero_subtitle",
            field=models.TextField(
                default="Automate inventory, accounts, sales insights, and reporting with intelligent AI assistance."
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="hero_title",
            field=models.CharField(
                default="Run your ERP with an AI Chatbot", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="primary_cta_label",
            field=models.CharField(default="Get Started", max_length=50),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="primary_cta_url",
            field=models.URLField(default="#pricing"),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="secondary_cta_label",
            field=models.CharField(default="Book Demo", max_length=50),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="secondary_cta_url",
            field=models.URLField(default="#demo"),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="seo_description",
            field=models.CharField(
                default="Automate your ERP operations with AI. Smart inventory, accounts, sales insights, and reporting.",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="seo_title",
            field=models.CharField(
                default="RoyalERP Chatbot - AI-Powered ERP Assistant", max_length=70
            ),
        ),
        migrations.AlterField(
            model_name="landingpagesettings",
            name="site_name",
            field=models.CharField(default="RoyalERP Chatbot", max_length=100),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="bullets",
            field=models.TextField(help_text="One feature per line"),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="cta_label",
            field=models.CharField(default="Get Started", max_length=50),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="cta_url",
            field=models.URLField(default="#"),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="period",
            field=models.CharField(blank=True, default="/month", max_length=50),
        ),
    ]
