# Generated by Django 6.0 on 2026-01-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0005_remove_landingpagesettings_faq_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="contact_address",
            field=models.CharField(
                blank=True, default="Bowery St, New York", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="contact@royalerp.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="contact_phone",
            field=models.CharField(blank=True, default="+1 234 567 890", max_length=20),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="hero_tagline",
            field=models.CharField(
                default="Automate your conversations and boost your marketing strategy",
                help_text="Tagline shown in mobile menu",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="social_facebook",
            field=models.URLField(
                blank=True, default="", help_text="Facebook page URL"
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="social_instagram",
            field=models.URLField(
                blank=True, default="", help_text="Instagram profile URL"
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="social_linkedin",
            field=models.URLField(
                blank=True, default="", help_text="LinkedIn page URL"
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="social_twitter",
            field=models.URLField(
                blank=True, default="", help_text="Twitter/X profile URL"
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="social_whatsapp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="WhatsApp number with country code",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="social_youtube",
            field=models.URLField(
                blank=True, default="", help_text="YouTube channel URL"
            ),
        ),
    ]
