# Generated by Django 6.0 on 2026-01-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0006_landingpagesettings_contact_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionblock",
            name="media_type",
            field=models.CharField(
                choices=[("IMAGE", "Image"), ("VIDEO", "Video")],
                default="IMAGE",
                help_text="Choose Image or Video",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sectionblock",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload MP4, WebM or OGG video",
                null=True,
                upload_to="landing/videos/",
            ),
        ),
        migrations.AddField(
            model_name="sectionblock",
            name="video_autoplay",
            field=models.BooleanField(
                default=True, help_text="Auto-play video (muted)"
            ),
        ),
        migrations.AddField(
            model_name="sectionblock",
            name="video_loop",
            field=models.BooleanField(
                default=True, help_text="Loop video continuously"
            ),
        ),
        migrations.AddField(
            model_name="sectionblock",
            name="video_poster",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail shown before video plays",
                null=True,
                upload_to="landing/videos/posters/",
            ),
        ),
    ]
