# Generated by Django 6.0 on 2026-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0007_sectionblock_media_type_sectionblock_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="pricing_subtitle",
            field=models.CharField(
                blank=True,
                default="Choose the plan that fits your business needs",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="pricing_title",
            field=models.CharField(
                default="Simple, Transparent Pricing 💰", max_length=200
            ),
        ),
    ]
