# Generated by Django 6.0 on 2026-01-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0008_landingpagesettings_pricing_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="integrations_subtitle",
            field=models.CharField(
                blank=True,
                default="Connect WhatsApp & Database for automated ERP responses",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="integrations_title",
            field=models.CharField(default="Seamless Integrations 🔗", max_length=200),
        ),
    ]
