# Generated by Django 6.0 on 2026-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0009_landingpagesettings_integrations_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="bullets",
            field=models.TextField(
                blank=True, help_text="Features list - one per line"
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short description of this integration"
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="icon_color",
            field=models.CharField(
                choices=[
                    ("green", "Green (WhatsApp style)"),
                    ("indigo", "Indigo/Blue (Database style)"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("orange", "Orange"),
                    ("gray", "Gray"),
                ],
                default="indigo",
                help_text="Background color for icon",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Show as main card (WhatsApp/Database style)"
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="icon_svg",
            field=models.TextField(
                blank=True, help_text="SVG code for icon (recommended)"
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="name",
            field=models.CharField(
                help_text="e.g., WhatsApp Integration, Database Connection",
                max_length=100,
            ),
        ),
    ]
