# Generated by Django 6.0 on 2026-01-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0010_integration_bullets_integration_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpagesettings",
            name="faq_subtitle",
            field=models.CharField(
                blank=True, default="Got questions? We've got answers.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="faq_title",
            field=models.CharField(
                default="Frequently Asked Questions ❓", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="reviews_subtitle",
            field=models.CharField(
                blank=True, default="Trusted by businesses worldwide", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="landingpagesettings",
            name="reviews_title",
            field=models.CharField(default="What Our Customers Say ⭐", max_length=200),
        ),
    ]
