# Generated by Django 6.0 on 2026-01-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0011_landingpagesettings_faq_subtitle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("features", "Features Section"),
                            ("automation", "Automation Section"),
                            ("integrations", "Integrations Section"),
                            ("pricing", "Pricing Section"),
                            ("reviews", "Reviews/Testimonials Section"),
                            ("faq", "FAQ Section"),
                            ("stats", "Stats Section"),
                            ("footer", "Footer Section"),
                        ],
                        help_text="Which section to display this image",
                        max_length=50,
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar/Profile"),
                            ("logo", "Logo/Brand"),
                            ("screenshot", "Screenshot"),
                            ("icon", "Icon"),
                            ("banner", "Banner"),
                            ("gallery", "Gallery Image"),
                        ],
                        default="avatar",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="landing/section_images/")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="One line subtitle/caption",
                        max_length=200,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility",
                        max_length=200,
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, help_text="Optional link when image is clicked"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Section Image",
                "verbose_name_plural": "Section Images",
                "ordering": ["section", "order"],
            },
        ),
    ]
