# Generated by Django 6.0 on 2026-01-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0012_sectionimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Feature image - will be displayed in the card with 3D effect",
                null=True,
                upload_to="landing/features/",
            ),
        ),
    ]
