# Generated by Django 6.0 on 2026-01-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0013_feature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="url",
            field=models.CharField(
                help_text="URL or anchor link (e.g., '#features' or 'https://example.com')",
                max_length=500,
            ),
        ),
    ]
